# Base da imagem Docker a ser utilizada
FROM python:3.9-alpine

# Copie arquivos ou pastas da origem para o caminho de destino no sistema de arquivos da imagem.
COPY . .

# Configura o contêiner para ser executado como um executável.
ENTRYPOINT ["python","script.py"]